### ISSUE TITLE
Bugs for 163 mirror

### ISSUE THREAD

**Issue by seisman** [yan9yu/CenDevEnv#3]
In commit 8f4b57b0c0f132eade9c70f52911528526e534c7, there are some possible bugs:

1. `lsb_release` is a command provided by `redhat-lsb-core`, which is not installed by default.

2. For CentOS 7.0 and 7.1, the output of `lsb_release` looks like:

        LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-
        Distributor ID:	CentOS
        Description:	CentOS Linux release 7.1.1503 (Core) 
        Release:	7.1.1503
        Codename:	Core

    So `grep` and `awk` command does not work for CentOS 7, may work for CentOS 5 or 6.

3. 163 mirror has only repo for CentOS 5 and 6, no repo for CentOS 7.

**Comment by yan9yu** [comment]
Hi @seisman, sorry for the late reply. 

1+2. Using `lsb_release` is just to ensure which CentOS version the system is. I don't know if there any other original and systemic command that can provide the same information.
3. I check the 163 mirror again, they do provide support for CentOS 7, check [here](http://mirrors.163.com/.help/centos.html) for more information.

BTW, I see your blog have some update about the environment setup stuff. It's better you can commit some of your ideas. :)
